apiVersion: v2
name: salt-minion
description: >
  Installs Salt minion Deployment and supporting configurations.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - salt
  - saltstack
  - compliance
  - cis
  - kubernetes
maintainers:
  - name: salt-compliance-team
