{{- if and .Values.agent.persistence.enabled (eq .Values.agent.persistence.type "pvc") (not .Values.agent.persistence.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salt-master-kubernetes-pki
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: salt-master-kubernetes
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  accessModes:
    - {{ .Values.agent.persistence.pvc.accessMode }}
  {{- with .Values.agent.persistence.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.agent.persistence.pvc.size }}
{{- end }}
