{{- $configName := printf "%s-minion-config" .Release.Name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ .Values.namespace }}
data:
  minion_id: {{ .Values.agent.minion.id | default (printf "%s-%s" .Release.Name .Release.Namespace) | quote }}
  master_id: {{ .Values.agent.minion.masterId | quote }}
  master_pub_key_b64: {{ .Values.agent.minion.masterPubKeyB64 | quote }}
